CREATE DATABASE ifri;
CREATE TABLE utilisateur (
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(100),
prenom VARCHAR(100),
email VARCHAR(255) NOT NULL UNIQUE,
mot_de_passe INT NOT NULL UNIQUE,
addresse VARCHAR(255),
driver_id INT,
passenger_id INT
);

CREATE TABLE driver (
id INT NOT NULL AUTO_INCREMENT ,
driver BOOLEAN);

CREATE TABLE passenger(
id INT NOT NULL AUTO_INCREMENT,
passenger BOOLEAN
)